
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 29 20:51:15 GMT+08:00 2026
//----------------------------------------------------

package myparser;

import java_cup.runtime.*;

/** CUP v0.10k generated parser.
  * @version Mon Jun 29 20:51:15 GMT+08:00 2026
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\055\000\002\003\005\000\002\002\004\000\002\004" +
    "\005\000\002\005\004\000\002\005\002\000\002\006\004" +
    "\000\002\006\002\000\002\007\004\000\002\007\004\000" +
    "\002\010\005\000\002\010\003\000\002\011\003\000\002" +
    "\011\003\000\002\012\004\000\002\012\002\000\002\013" +
    "\003\000\002\013\003\000\002\013\003\000\002\013\003" +
    "\000\002\013\003\000\002\014\005\000\002\015\010\000" +
    "\002\015\010\000\002\015\011\000\002\016\010\000\002" +
    "\017\006\000\002\017\002\000\002\020\005\000\002\021" +
    "\004\000\002\021\006\000\002\021\007\000\002\022\004" +
    "\000\002\023\005\000\002\023\002\000\002\024\003\000" +
    "\002\024\003\000\002\025\005\000\002\026\003\000\002" +
    "\026\003\000\002\026\003\000\002\026\003\000\002\027" +
    "\003\000\002\027\003\000\002\027\003\000\002\027\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\131\000\004\004\006\001\002\000\004\002\133\001" +
    "\002\000\026\002\ufffb\006\013\007\014\012\ufffb\015\ufffb" +
    "\017\ufffb\021\ufffb\022\ufffb\041\ufffb\042\ufffb\001\002\000" +
    "\004\040\007\001\002\000\030\002\ufffd\005\010\006\ufffd" +
    "\007\ufffd\012\ufffd\015\ufffd\017\ufffd\021\ufffd\022\ufffd\041" +
    "\ufffd\042\ufffd\001\002\000\004\037\012\001\002\000\026" +
    "\002\uffff\006\uffff\007\uffff\012\uffff\015\uffff\017\uffff\021" +
    "\uffff\022\uffff\041\uffff\042\uffff\001\002\000\026\002\ufffe" +
    "\006\ufffe\007\ufffe\012\ufffe\015\ufffe\017\ufffe\021\ufffe\022" +
    "\ufffe\041\ufffe\042\ufffe\001\002\000\006\041\025\042\034" +
    "\001\002\000\006\041\025\042\034\001\002\000\022\002" +
    "\ufff3\012\021\015\031\017\036\021\035\022\020\041\025" +
    "\042\034\001\002\000\026\002\ufffb\006\013\007\014\012" +
    "\ufffb\015\ufffb\017\ufffb\021\ufffb\022\ufffb\041\ufffb\042\ufffb" +
    "\001\002\000\022\002\ufffc\012\ufffc\015\ufffc\017\ufffc\021" +
    "\ufffc\022\ufffc\041\ufffc\042\ufffc\001\002\000\006\025\120" +
    "\040\117\001\002\000\012\023\105\037\041\041\025\042" +
    "\034\001\002\000\024\002\ufff2\012\ufff2\015\ufff2\017\ufff2" +
    "\021\ufff2\022\ufff2\024\ufff2\041\ufff2\042\ufff2\001\002\000" +
    "\024\002\uffee\012\uffee\015\uffee\017\uffee\021\uffee\022\uffee" +
    "\024\uffee\041\uffee\042\uffee\001\002\000\024\002\ufff0\012" +
    "\ufff0\015\ufff0\017\ufff0\021\ufff0\022\ufff0\024\ufff0\041\ufff0" +
    "\042\ufff0\001\002\000\064\002\ufff6\006\ufff6\007\ufff6\010" +
    "\ufff6\011\ufff6\012\ufff6\013\ufff6\015\ufff6\016\ufff6\017\ufff6" +
    "\021\ufff6\022\ufff6\023\ufff6\024\ufff6\026\ufff6\027\ufff6\030" +
    "\ufff6\031\ufff6\032\ufff6\033\ufff6\034\ufff6\035\ufff6\036\ufff6" +
    "\041\ufff6\042\ufff6\001\002\000\004\011\103\001\002\000" +
    "\004\002\001\001\002\000\024\002\ufff3\012\021\015\031" +
    "\017\036\021\035\022\020\024\ufff3\041\025\042\034\001" +
    "\002\000\010\037\041\041\025\042\034\001\002\000\024" +
    "\002\ufff1\012\ufff1\015\ufff1\017\ufff1\021\ufff1\022\ufff1\024" +
    "\ufff1\041\ufff1\042\ufff1\001\002\000\024\002\uffef\012\uffef" +
    "\015\uffef\017\uffef\021\uffef\022\uffef\024\uffef\041\uffef\042" +
    "\uffef\001\002\000\064\002\ufff5\006\ufff5\007\ufff5\010\ufff5" +
    "\011\ufff5\012\ufff5\013\ufff5\015\ufff5\016\ufff5\017\ufff5\021" +
    "\ufff5\022\ufff5\023\ufff5\024\ufff5\026\ufff5\027\ufff5\030\ufff5" +
    "\031\ufff5\032\ufff5\033\ufff5\034\ufff5\035\ufff5\036\ufff5\041" +
    "\ufff5\042\ufff5\001\002\000\004\040\072\001\002\000\010" +
    "\037\041\041\025\042\034\001\002\000\054\002\uffdf\012" +
    "\uffdf\013\uffdf\015\uffdf\016\uffdf\017\uffdf\021\uffdf\022\uffdf" +
    "\023\uffdf\024\uffdf\026\uffdf\027\uffdf\030\uffdf\031\uffdf\032" +
    "\uffdf\033\uffdf\034\uffdf\035\uffdf\036\uffdf\041\uffdf\042\uffdf" +
    "\001\002\000\054\002\uffe0\012\uffe0\013\uffe0\015\uffe0\016" +
    "\uffe0\017\uffe0\021\uffe0\022\uffe0\023\uffe0\024\uffe0\026\uffe0" +
    "\027\064\030\065\031\066\032\067\033\uffe0\034\uffe0\035" +
    "\uffe0\036\uffe0\041\uffe0\042\uffe0\001\002\000\054\002\uffde" +
    "\012\uffde\013\uffde\015\uffde\016\uffde\017\uffde\021\uffde\022" +
    "\uffde\023\uffde\024\uffde\026\uffde\027\uffde\030\uffde\031\uffde" +
    "\032\uffde\033\uffde\034\uffde\035\uffde\036\uffde\041\uffde\042" +
    "\uffde\001\002\000\012\033\055\034\057\035\056\036\060" +
    "\001\002\000\004\023\044\001\002\000\022\012\021\015" +
    "\031\017\036\021\035\022\020\024\ufff3\041\025\042\034" +
    "\001\002\000\004\024\046\001\002\000\026\002\uffe7\012" +
    "\uffe7\015\uffe7\017\uffe7\020\047\021\uffe7\022\uffe7\024\uffe7" +
    "\041\uffe7\042\uffe7\001\002\000\004\023\051\001\002\000" +
    "\024\002\uffe9\012\uffe9\015\uffe9\017\uffe9\021\uffe9\022\uffe9" +
    "\024\uffe9\041\uffe9\042\uffe9\001\002\000\022\012\021\015" +
    "\031\017\036\021\035\022\020\024\ufff3\041\025\042\034" +
    "\001\002\000\004\024\053\001\002\000\024\002\uffe8\012" +
    "\uffe8\015\uffe8\017\uffe8\021\uffe8\022\uffe8\024\uffe8\041\uffe8" +
    "\042\uffe8\001\002\000\010\037\041\041\025\042\034\001" +
    "\002\000\010\037\uffd8\041\uffd8\042\uffd8\001\002\000\010" +
    "\037\uffd6\041\uffd6\042\uffd6\001\002\000\010\037\uffd7\041" +
    "\uffd7\042\uffd7\001\002\000\010\037\uffd5\041\uffd5\042\uffd5" +
    "\001\002\000\026\002\uffdd\012\uffdd\015\uffdd\017\uffdd\021" +
    "\uffdd\022\uffdd\023\uffdd\024\uffdd\041\uffdd\042\uffdd\001\002" +
    "\000\044\002\uffe2\012\uffe2\013\uffe2\015\uffe2\016\uffe2\017" +
    "\uffe2\021\uffe2\022\uffe2\023\uffe2\024\uffe2\026\uffe2\033\uffe2" +
    "\034\uffe2\035\uffe2\036\uffe2\041\uffe2\042\uffe2\001\002\000" +
    "\010\037\041\041\025\042\034\001\002\000\010\037\uffdc" +
    "\041\uffdc\042\uffdc\001\002\000\010\037\uffdb\041\uffdb\042" +
    "\uffdb\001\002\000\010\037\uffda\041\uffda\042\uffda\001\002" +
    "\000\010\037\uffd9\041\uffd9\042\uffd9\001\002\000\054\002" +
    "\uffe0\012\uffe0\013\uffe0\015\uffe0\016\uffe0\017\uffe0\021\uffe0" +
    "\022\uffe0\023\uffe0\024\uffe0\026\uffe0\027\064\030\065\031" +
    "\066\032\067\033\uffe0\034\uffe0\035\uffe0\036\uffe0\041\uffe0" +
    "\042\uffe0\001\002\000\044\002\uffe1\012\uffe1\013\uffe1\015" +
    "\uffe1\016\uffe1\017\uffe1\021\uffe1\022\uffe1\023\uffe1\024\uffe1" +
    "\026\uffe1\033\uffe1\034\uffe1\035\uffe1\036\uffe1\041\uffe1\042" +
    "\uffe1\001\002\000\006\041\025\042\034\001\002\000\024" +
    "\002\uffe6\012\uffe6\015\uffe6\017\uffe6\021\uffe6\022\uffe6\024" +
    "\uffe6\041\uffe6\042\uffe6\001\002\000\004\016\075\001\002" +
    "\000\010\037\041\041\025\042\034\001\002\000\004\023" +
    "\077\001\002\000\022\012\021\015\031\017\036\021\035" +
    "\022\020\024\ufff3\041\025\042\034\001\002\000\004\024" +
    "\101\001\002\000\024\002\uffea\012\uffea\015\uffea\017\uffea" +
    "\021\uffea\022\uffea\024\uffea\041\uffea\042\uffea\001\002\000" +
    "\006\002\ufff4\024\ufff4\001\002\000\010\037\041\041\025" +
    "\042\034\001\002\000\024\002\uffed\012\uffed\015\uffed\017" +
    "\uffed\021\uffed\022\uffed\024\uffed\041\uffed\042\uffed\001\002" +
    "\000\022\012\021\015\031\017\036\021\035\022\020\024" +
    "\ufff3\041\025\042\034\001\002\000\004\013\107\001\002" +
    "\000\004\023\110\001\002\000\022\012\021\015\031\017" +
    "\036\021\035\022\020\024\ufff3\041\025\042\034\001\002" +
    "\000\004\024\112\001\002\000\024\002\uffec\012\uffec\015" +
    "\uffec\017\uffec\021\uffec\022\uffec\024\uffec\041\uffec\042\uffec" +
    "\001\002\000\004\024\114\001\002\000\004\014\115\001" +
    "\002\000\010\037\041\041\025\042\034\001\002\000\024" +
    "\002\uffeb\012\uffeb\015\uffeb\017\uffeb\021\uffeb\022\uffeb\024" +
    "\uffeb\041\uffeb\042\uffeb\001\002\000\026\002\uffe5\012\uffe5" +
    "\015\uffe5\017\uffe5\021\uffe5\022\uffe5\024\uffe5\025\123\041" +
    "\uffe5\042\uffe5\001\002\000\010\037\041\041\025\042\034" +
    "\001\002\000\004\026\122\001\002\000\024\002\uffe4\012" +
    "\uffe4\015\uffe4\017\uffe4\021\uffe4\022\uffe4\024\uffe4\041\uffe4" +
    "\042\uffe4\001\002\000\010\037\041\041\025\042\034\001" +
    "\002\000\004\026\125\001\002\000\024\002\uffe3\012\uffe3" +
    "\015\uffe3\017\uffe3\021\uffe3\022\uffe3\024\uffe3\041\uffe3\042" +
    "\uffe3\001\002\000\030\002\ufff7\006\ufff7\007\ufff7\010\130" +
    "\012\ufff7\015\ufff7\017\ufff7\021\ufff7\022\ufff7\041\ufff7\042" +
    "\ufff7\001\002\000\026\002\ufff9\006\ufff9\007\ufff9\012\ufff9" +
    "\015\ufff9\017\ufff9\021\ufff9\022\ufff9\041\ufff9\042\ufff9\001" +
    "\002\000\006\041\025\042\034\001\002\000\026\002\ufff8" +
    "\006\ufff8\007\ufff8\012\ufff8\015\ufff8\017\ufff8\021\ufff8\022" +
    "\ufff8\041\ufff8\042\ufff8\001\002\000\026\002\ufffa\006\ufffa" +
    "\007\ufffa\012\ufffa\015\ufffa\017\ufffa\021\ufffa\022\ufffa\041" +
    "\ufffa\042\ufffa\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\131\000\006\003\003\004\004\001\001\000\002\001" +
    "\001\000\006\006\014\007\015\001\001\000\002\001\001" +
    "\000\004\005\010\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\010\131\011\125\001\001" +
    "\000\006\010\126\011\125\001\001\000\022\011\025\012" +
    "\026\013\027\014\021\015\031\016\023\020\032\021\022" +
    "\001\001\000\006\006\016\007\015\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\011\036\022\105\024\037" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\011\025\012\101\013\027\014\021\015\031\016" +
    "\023\020\032\021\022\001\001\000\010\011\036\022\073" +
    "\024\037\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\011\036\022\041" +
    "\024\037\025\042\001\001\000\002\001\001\000\006\023" +
    "\061\026\062\001\001\000\002\001\001\000\004\027\053" +
    "\001\001\000\002\001\001\000\022\011\025\012\044\013" +
    "\027\014\021\015\031\016\023\020\032\021\022\001\001" +
    "\000\002\001\001\000\004\017\047\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\011\025\012\051\013\027" +
    "\014\021\015\031\016\023\020\032\021\022\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\011\036\022\060" +
    "\024\037\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\011\036\024\067\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\023\070\026\062\001\001\000\002\001\001\000" +
    "\004\011\072\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\011\036\022\075\024\037\001\001\000\002\001" +
    "\001\000\022\011\025\012\077\013\027\014\021\015\031" +
    "\016\023\020\032\021\022\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\011\036\022\103" +
    "\024\037\001\001\000\002\001\001\000\022\011\025\012" +
    "\112\013\027\014\021\015\031\016\023\020\032\021\022" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\011" +
    "\025\012\110\013\027\014\021\015\031\016\023\020\032" +
    "\021\022\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\011\036\022\041" +
    "\024\037\025\115\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\011\036\022\120\024\037\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\011\036\022\123\024" +
    "\037\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\010\130\011\125\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // logical ::= NOT_EQUALS 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(21/*logical*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // logical ::= EQUALS 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(21/*logical*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // logical ::= GREATER_THAN 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(21/*logical*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // logical ::= LESS_THAN 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(21/*logical*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // operation ::= MULTIPLY 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*operation*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // operation ::= DIVIDE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*operation*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // operation ::= MINUS 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*operation*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // operation ::= PLUS 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*operation*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // condition ::= expression logical expression 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(19/*condition*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // term ::= NUMBER 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*term*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // term ::= variable 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*term*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expression_prime ::= 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(17/*expression_prime*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expression_prime ::= operation term expression_prime 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(17/*expression_prime*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expression ::= term expression_prime 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(16/*expression*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // output ::= PRINT_TOKEN STRING_LITERAL LPAREN expression RPAREN 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(15/*output*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // output ::= PRINT_TOKEN LPAREN expression RPAREN 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(15/*output*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // output ::= PRINT_TOKEN STRING_LITERAL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(15/*output*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // input ::= INPUT_TOKEN STRING_LITERAL variable 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(14/*input*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // else ::= 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(13/*else*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // else ::= ELSE_TOKEN LBRACE statements RBRACE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(13/*else*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // conditional ::= IF_TOKEN condition LBRACE statements RBRACE else 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(12/*conditional*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // repetition ::= FROM expression TO expression LBRACE statements RBRACE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(11/*repetition*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // repetition ::= REPEAT LBRACE statements RBRACE UNTIL condition 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(11/*repetition*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // repetition ::= REPEAT expression TIMES LBRACE statements RBRACE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(11/*repetition*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // assignment ::= variable ASSIGN expression 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*assignment*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // statement ::= output 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // statement ::= input 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // statement ::= conditional 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // statement ::= repetition 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // statement ::= assignment 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // statements ::= 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(8/*statements*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // statements ::= statement statements 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(8/*statements*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // variable ::= TEXTVAL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(7/*variable*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // variable ::= NUMVAL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(7/*variable*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // varlist ::= variable 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(6/*varlist*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // varlist ::= variable COMMA varlist 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(6/*varlist*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declaration ::= STRING varlist 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*declaration*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declaration ::= NUM varlist 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*declaration*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declarations ::= 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*declarations*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declarations ::= declaration declarations 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*declarations*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // optional_id ::= 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*optional_id*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // optional_id ::= ID NUMBER 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*optional_id*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // identification ::= NAME STRING_LITERAL optional_id 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*identification*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= identification declarations statements 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(1/*program*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

