
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 30 18:53:15 GMT+08:00 2026
//----------------------------------------------------

package myparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 9;
  public static final int FROM = 11;
  public static final int MULTIPLY = 24;
  public static final int PLUS = 21;
  public static final int RPAREN = 20;
  public static final int RBRACE = 18;
  public static final int GREATER_THAN = 26;
  public static final int INPUT_TOKEN = 15;
  public static final int ELSE_TOKEN = 14;
  public static final int NAME = 2;
  public static final int LPAREN = 19;
  public static final int LBRACE = 17;
  public static final int NUMVAL = 31;
  public static final int ID = 3;
  public static final int NUM = 4;
  public static final int STRING_LITERAL = 30;
  public static final int EQUALS = 27;
  public static final int STRING = 5;
  public static final int COMMA = 6;
  public static final int NUMBER = 29;
  public static final int EOF = 0;
  public static final int DIVIDE = 23;
  public static final int LESS_THAN = 25;
  public static final int MINUS = 22;
  public static final int NOT_EQUALS = 28;
  public static final int error = 1;
  public static final int TEXTVAL = 32;
  public static final int UNTIL = 10;
  public static final int ASSIGN = 7;
  public static final int PRINT_TOKEN = 16;
  public static final int TO = 12;
  public static final int REPEAT = 8;
  public static final int IF_TOKEN = 13;
}

